version: '3.3'
services:
  php:
    build: .
    volumes:
      - ./:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    links:
      - mysql

  mysql:    
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: inforvic_db
      MYSQL_USER: samu
      MYSQL_PASSWORD: 123456
    ports:
      - 9999:3306
      
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
    ports:
      - 8090:80
